name: Python package CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install setuptools wheel twine build pytest

      - name: Build package
        run: python -m build

      - name: Test package
        run: python -m pytest
  
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip and UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Create and activate virtual environment
        run: |
          uv venv .venv
          echo ".venv/bin/activate" >> $GITHUB_ENV

      - name: Install dependencies with UV
        run: |
          source .venv/bin/activate
          uv pip install setuptools wheel twine

      - name: Build package
        run: |
          source .venv/bin/activate
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          source .venv/bin/activate
          uv twine upload dist/*
