name: Python package CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip and UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with UV
        run: uv pip install setuptools wheel twine pytest

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Test package
        run: uv pip install . && uv pytest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip and UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with UV
        run: uv pip install setuptools wheel twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: uv twine upload dist/*
